export const cards = [
  {
    id: 1,
    title: "Haircuts",
    img: "/../../photo6.avif",
  },
  {
    id: 2,
    title: "Beard Services",
    img: "/../../photo7.avif",
  },
  {
    id: 3,
    title: "Hairstyling",
    img: "/../../photo99.jpg",
  },
  {
    id: 4,
    title: "Coloring",
    img: "/../../photo98.jpg",
  },
  {
    id: 5,
    title: "Massaging",
    img: "/../../photo97.jpg",
  },
  {
    id: 6,
    title: "Facial treatments",
    img: "/../../photo96.jpg",
  },
  {
    id: 7,
    title: "Kids' cuts",
    img: "/../../jpg95.jpg",
  },
];

export const projects = [
  {
    id: 1,
    img: "/../../photo94.png",
    pp: "/../../photo80.jpg",
    cat: "Manoj jents Parlour",
    username: "Manoj sharma",
  },
  {
    id: 2,
    img: "/../../photo92.png",
    pp: "/../../photo79.jpg",
    cat: "Bansi Hair Dresser",
    username: "Bansi lal pandey",
  },
  {
    id: 3,
    img: "/../../photo91.png",
    pp: "/../../photo78.jpg",
    cat: "Kajol saloon",
    username: "kamlesh",
  },
  {
    id: 4,
    img: "/../../photo90.png",
    pp: "/../../photo77.jpg",
    cat: "Golden scissor saloon",
    username: "Sumit saini",
  },
  {
    id: 5,
    img: "/../../photo89.png",
    pp: "/../../photo76.jpg",
    cat: "Star hair art",
    username: "Rajat verma",
  },
  {
    id: 6,
    img: "/../../photo88.png",
    pp: "/../../photo75.jpg",
    cat: "vicky's saloon",
    username: "vicky sethi",
  },
  {
    id: 7,
    img: "/../../photo87.png",
    pp: "/../../photo74.jpg",
    cat: "New S.R hair dresser",
    username: "Sikander singh",
  },
  {
    id: 8,
    img: "/../../photo86.png",
    pp: "/../../photo73.jpg",
    cat: "Rakesh Gents A.c Parlour",
    username: "Rakesh gautam",
  },
];

export const gigs = [
  {
    id: 1,
    img: "https://images.pexels.com/photos/580151/pexels-photo-580151.jpeg?auto=compress&cs=tinysrgb&w=1600",
    pp: "https://images.pexels.com/photos/720598/pexels-photo-720598.jpeg?auto=compress&cs=tinysrgb&w=1600",
    desc: "I will create ai art character from your images and prompts",
    price: 59,
    star: 5,
    username: "Anna Bell",
  },
  {
    id: 2,
    img: "https://images.pexels.com/photos/4145190/pexels-photo-4145190.jpeg?auto=compress&cs=tinysrgb&w=1600",
    pp: "https://images.pexels.com/photos/1036627/pexels-photo-1036627.jpeg?auto=compress&cs=tinysrgb&w=1600",
    desc: "I will create ultra high quality character art with ai",
    price: 79,
    star: 5,
    username: "Lannie Coleman",
  },
  {
    id: 3,
    img: "https://images.pexels.com/photos/8797307/pexels-photo-8797307.jpeg?auto=compress&cs=tinysrgb&w=1600",
    pp: "https://images.pexels.com/photos/1062280/pexels-photo-1062280.jpeg?auto=compress&cs=tinysrgb&w=1600",
    desc: "I will creating unique ai generated artworks mid journey ai artist",
    price: 112,
    star: 5,
    username: "Carol Steve",
  },
  {
    id: 4,
    img: "https://images.pexels.com/photos/5708069/pexels-photo-5708069.jpeg?auto=compress&cs=tinysrgb&w=1600",
    pp: "https://images.pexels.com/photos/1681010/pexels-photo-1681010.jpeg?auto=compress&cs=tinysrgb&w=1600",
    desc: "I will create custom ai generated artwork using your photos",
    price: 99,
    star: 4,
    username: "Don Weber",
  },
  {
    id: 5,
    img: "https://images.pexels.com/photos/5699456/pexels-photo-5699456.jpeg?auto=compress&cs=tinysrgb&w=1600",
    pp: "https://images.pexels.com/photos/1771383/pexels-photo-1771383.jpeg?auto=compress&cs=tinysrgb&w=1600",
    desc: "I will recreate your dreams in high quality pictures",
    price: 59,
    star: 5,
    username: "Audrey Richards",
  },
  {
    id: 6,
    img: "https://images.pexels.com/photos/8100784/pexels-photo-8100784.jpeg?auto=compress&cs=tinysrgb&w=1600",
    pp: "https://images.pexels.com/photos/715546/pexels-photo-715546.jpeg?auto=compress&cs=tinysrgb&w=1600",
    desc: "I will create ai digital art illustration hyper realistic painting",
    price: 79,
    star: 4,
    username: "Walton Shepard ",
  },
  {
    id: 7,
    img: "https://images.pexels.com/photos/6039245/pexels-photo-6039245.jpeg?auto=compress&cs=tinysrgb&w=1600",
    pp: "https://images.pexels.com/photos/720606/pexels-photo-720606.jpeg?auto=compress&cs=tinysrgb&w=1600",
    desc: "I will generate images with your prompts using ai dalle",
    price: 89,
    star: 5,
    username: "Waverly Schaefer",
  },
  {
    id: 8,
    img: "https://images.pexels.com/photos/5490778/pexels-photo-5490778.jpeg?auto=compress&cs=tinysrgb&w=1600",
    pp: "https://images.pexels.com/photos/1699159/pexels-photo-1699159.jpeg?auto=compress&cs=tinysrgb&w=1600",
    desc: "I will create custom art using midjourney generator",
    price: 110,
    star: 4,
    username: "Wilton Hunt",
  },
];
